name: Build
on:
  pull_request:
    branches:
      - dev-test
  push:
    branches:
      - dev-test
jobs:
    build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: "3.9"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run ruff
        run: ruff .
      - name: Build coverage file
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
